[project]
name = "adventofcode"
version = "0.1.0"
description = "Advent of code solutions in python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hypothesis>=6.122.0",
    "matplotlib>=3.9.3",
    "pytest>=8.3.3",
    "requests>=2.32.3",
    "ruff>=0.8.1",
]
